@ECHO OFF

IF DEFINED __TRANSVERSE_DOMAIN_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TRANSVERSE_DOMAIN_COMMON_PATHES_EXECUTED__=yes


SET __d__CURRENT_SCRIPT_PATH__d__=%~dp0


SET TRANSVERSE_DOMAIN_COMMON_PATH=%__d__CURRENT_SCRIPT_PATH__d__%
SET TRANSVERSE_DOMAIN_PATH=%TRANSVERSE_DOMAIN_COMMON_PATH%..



REM ------ Dépendance vis-à-vis de la couche _COMMON ----------
SET TRANSVERSE_COMMON_PATH=%TRANSVERSE_DOMAIN_PATH%/../Transverse._Common

CALL "%TRANSVERSE_COMMON_PATH%/_Pathes.bat"





REM -------------------- Chemins (et scripts) dans Transverse.Domain --------------------------------------

SET TRANSVERSE_DOMAIN_DISK_ELEMENTS_PATH=%TRANSVERSE_DOMAIN_PATH%/DiskElements
SET TRANSVERSE_DOMAIN_DISK_ELEMENTS_DISKELEMENTS_SCRIPT=%TRANSVERSE_DOMAIN_DISK_ELEMENTS_PATH%/DiskElements.bat

