@ECHO OFF

SET _$$__inf$_CURRENT_SCRIPT_PATH_$inf__$$_=%~dp0

SET TESTING_LIB_INFRA_PATH=%_$$__inf$_CURRENT_SCRIPT_PATH_$inf__$$_%..
SET TESTING_LIB_INFRA_COMMON_PATH=%TESTING_LIB_INFRA_PATH%/_Common

REM Recup. de TESTING_LIB_INFRA_DI_PATH
CALL "%TESTING_LIB_INFRA_COMMON_PATH%/_Pathes.bat"


@REM CALL "%TESTING_LIB_INFRA_DI_PATH%/xxxx.bat" %1 %2 %3 %4 %5 %6 %7 %8 %9