@ECHO OFF

@REM SET _$$__$CURRENT_NAMESPACE$__$$_=TestingLib.Infra
SET _$$__$_CURRENT_SCRIPT_PATH_$__$$_=%~dp0

SET TESTING_LIB_INFRA_PATH=%_$$__$_CURRENT_SCRIPT_PATH_$__$$_%..
SET TESTING_LIB_INFRA_COMMON_PATH=%TESTING_LIB_INFRA_PATH%/_Common

REM Recup. de TESTING_LIB_INFRA_REPOSITORIES_PATH
CALL "%TESTING_LIB_INFRA_COMMON_PATH%/_Pathes.bat"




REM ------------------- "Injection" ---------------------
REM        Met en fait en global des var. d'env.

SET TESTING_LIB_MESSAGES_LABEL_REPOSITORY_SCRIPT=%TESTING_LIB_INFRA_REPOSITORIES_MESSAGES_LABEL_REPOSITORY_SCRIPT%
SET TESTING_LIB_DISK_ELEMENTS_SERVICE_SCRIPT=%TESTING_LIB_INFRA_DISK_ELEMENTS_SERVICE_SCRIPT%