@ECHO OFF

IF DEFINED __TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_EXECUTED__ GOTO :EOF
SET __TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_EXECUTED__=yes


REM --- Id des résultats d'assertion ---
SET TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_SUCCESS_ID=SUCCESS_ID
SET TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_FAILURE_ID=FAILURE_ID