@ECHO OFF

SET __dd__CURRENT_SCRIPT_PATH__dd__=%~dp0


SET TESTING_LIB_DOMAIN_COMMON_PATH=%__dd__CURRENT_SCRIPT_PATH__dd__%
SET TESTING_LIB_DOMAIN_PATH=%TESTING_LIB_DOMAIN_COMMON_PATH%..



REM ------ Dépendance vis-à-vis de la couche _COMMON ----------
SET TESTING_LIB_COMMON_PATH=%TESTING_LIB_DOMAIN_PATH%/../TestingLib._Common

CALL "%TESTING_LIB_COMMON_PATH%/_Pathes.bat"





REM -------------------- Chemins (et scripts) dans TestingLib.Domain --------------------------------------

SET TESTING_LIB_DOMAIN_COMMON_ENUMS_PATH=%TESTING_LIB_DOMAIN_COMMON_PATH%Enums
SET TESTING_LIB_DOMAIN_COMMON_SERVICES_PATH=%TESTING_LIB_DOMAIN_COMMON_PATH%Services