@ECHO OFF

IF DEFINED __TESTING_API_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TESTING_API_COMMON_PATHES_EXECUTED__=yes


SET __ii__CURRENT_SCRIPT_PATH__ii__=%~dp0


SET TESTING_API_COMMON_PATH=%__ii__CURRENT_SCRIPT_PATH__ii__%
SET TESTING_API_PATH=%TESTING_API_COMMON_PATH%..


REM PONT VERS Transverse.API
CALL "%TESTING_API_COMMON_PATH%_PathesToTransverse.bat"




REM ------ Dépendance vis-à-vis de la couche APPLICATION ----------
SET TESTING_APPLICATION_PATH=%TESTING_API_PATH%/../Application
SET TESTING_APPLICATION_COMMON_PATH=%TESTING_APPLICATION_PATH%/_Common

CALL "%TESTING_APPLICATION_COMMON_PATH%/_Pathes.bat"






REM -------------------- Chemins (et scripts) dans zzzTesting/API --------------------------------------

SET TESTING_API_DI_PATH=%TESTING_API_PATH%/DI

SET TESTING_API_CONTROLLERS_PATH=%TESTING_API_PATH%/Controllers
SET TESTING_API_CONTROLLERS_FRONT_CONTROLLER_SCRIPT=%TESTING_API_CONTROLLERS_PATH%/_FrontController.bat
SET TESTING_API_DI_PATH=%TESTING_API_PATH%/DI


