@ECHO OFF
REM ---------------- SCRIPT DE DECOUPLAGE/ADAPTATION POUR LIER LES 2 MONDES : ------------------
REM   à savoir : ma présente Architecture Transverse (partie TESTS/)   
REM              ET   une librairie externe comprenant des outils pour Testing.


SET $z$_$CURRENT_SCRIPT_PATH$_$z$=%~dp0
SET TESTS_COMMON_PATH=%$z$_$CURRENT_SCRIPT_PATH$_$z$%Transverse._Common



REM --------- Choix de la Lib. Externe de Testing ----------
SET EXTERNAL_TESTING_LIB_PATH=%TESTS_COMMON_PATH%/../_ExternalTestingLib

SET EXTERNAL_TESTING_LIB_INFRA_PATH=%EXTERNAL_TESTING_LIB_PATH%/TestingLib.Infra
SET EXTERNAL_TESTING_LIB_INFRA_API_PATH=%EXTERNAL_TESTING_LIB_INFRA_PATH%/API
SET EXTERNAL_TESTING_LIB_INFRA_API_ENUMS_PATH=%EXTERNAL_TESTING_LIB_INFRA_API_PATH%/Enums
SET EXTERNAL_TESTING_LIB_INFRA_API_FRONT_CONTROLLER_SCRIPT=%EXTERNAL_TESTING_LIB_INFRA_API_PATH%/_FrontController.bat


Rem Recup. de TESTING_LIB_INFRA_API_ENUMS__ASSERTION_RESULT_DISPLAYER_SCRIPT_ID
CALL "%EXTERNAL_TESTING_LIB_INFRA_API_ENUMS_PATH%/Scripts.bat"
SET EXTERNAL_TESTING_LIB_INFRA_API_ENUMS__ASSERTION_RESULT_DISPLAYER_SCRIPT_ID=%TESTING_LIB_INFRA_API_ENUMS__ASSERTION_RESULT_DISPLAYER_SCRIPT_ID%



REM ------ Params fixes pour les appels qu'on effectera vers la librairie externe ------
CALL "%EXTERNAL_TESTING_LIB_INFRA_PATH%/_Init.bat"

SET EXTERNAL_TESTING_LIB_MESSAGES_DISPLAYER=%MESSAGES_DISPLAYER%
SET EXTERNAL_TESTING_LIB_MESSAGES_LANG_ID=US


REM =====================================================================================================================================
SET EXTERNAL_TESTING_LIB_ASSERTION_RESULT_DISPLAYER_SCRIPT=
CALL "%EXTERNAL_TESTING_LIB_INFRA_API_FRONT_CONTROLLER_SCRIPT%" Scripts Get EXTERNAL_TESTING_LIB_ASSERTION_RESULT_DISPLAYER_SCRIPT "%EXTERNAL_TESTING_LIB_INFRA_API_ENUMS__ASSERTION_RESULT_DISPLAYER_SCRIPT_ID%"
@REM ECHO EXTERNAL_TESTING_LIB_ASSERTION_RESULT_DISPLAYER_SCRIPT='!EXTERNAL_TESTING_LIB_ASSERTION_RESULT_DISPLAYER_SCRIPT!'



REM ==================== ACTIONS en fonction des params reçus ====================================	
REM ---- Pour appel aux Functions utilitaires de la librairie externe ----
SET __ASSERTION_RESULT__=
IF %1. EQU AssertAreEqual. (

    Rem Comparaison de %2 et %3
    CALL "%EXTERNAL_TESTING_LIB_INFRA_API_FRONT_CONTROLLER_SCRIPT%" AssertionResult GetEqualityAssertionResult __ASSERTION_RESULT__ %2 %3

)
ECHO __ASSERTION_RESULT__=!__ASSERTION_RESULT__!

@REM CALL "!EXTERNAL_TESTING_LIB_ASSERTION_RESULT_DISPLAYER_SCRIPT!" AssertAreEqual "%EXTERNAL_TESTING_LIB_MESSAGES_LANG_ID%" "%EXTERNAL_TESTING_LIB_MESSAGES_DISPLAYER%" "!__ASSERTION_RESULT__!" %2 %3 %4

GOTO :EOF