@ECHO OFF

SET __aa__CURRENT_SCRIPT_PATH__aa__=%~dp0


SET TESTING_LIB_APPLICATION_COMMON_PATH=%__aa__CURRENT_SCRIPT_PATH__aa__%
SET TESTING_LIB_APPLICATION_PATH=%TESTING_LIB_APPLICATION_COMMON_PATH%..



REM ------ Dépendance vis-à-vis de la couche DOMAIN ----------
SET TESTING_LIB_DOMAIN_PATH=%TESTING_LIB_APPLICATION_PATH%/../TestingLib.Domain
SET TESTING_LIB_DOMAIN_COMMON_PATH=%TESTING_LIB_DOMAIN_PATH%/_Common

CALL "%TESTING_LIB_DOMAIN_COMMON_PATH%/_Pathes.bat"







REM -------------------- Chemins (et scripts) dans TestingLib.Application --------------------------------------

SET TESTING_LIB_APPLICATION_USE_CASES_PATH=%TESTING_LIB_APPLICATION_PATH%/UseCases
SET TESTING_LIB_APPLICATION_USE_CASES_MAPPERS_PATH=%TESTING_LIB_APPLICATION_USE_CASES_PATH%/Mappers
SET TESTING_LIB_APPLICATION_USE_CASES_MAPPERS_DOMAIN_TO_EXTERNAL_WORLD=%TESTING_LIB_APPLICATION_USE_CASES_MAPPERS_PATH%/DomainToExternalWorld.bat

SET TESTING_LIB_APPLICATION_USE_CASES_MAPPERS_DOMAIN_TO_EXTERNAL_WORLD_SCRIPT=%TESTING_LIB_APPLICATION_USE_CASES_MAPPERS_PATH%/DomainToExternalWorld.bat

SET TESTING_LIB_APPLICATION_ENUMS=%TESTING_LIB_APPLICATION_PATH%/Enums
SET TESTING_LIB_APPLICATION_ENUMS_ASSERTION_RESULT_SCRIPT=%TESTING_LIB_APPLICATION_ENUMS%/AssertionResult.bat


SET TESTING_LIB_APPLICATION_COMMON_SERVICES_PATH=%TESTING_LIB_APPLICATION_COMMON_PATH%Services

