@ECHO OFF

SET __aa__CURRENT_SCRIPT_PATH__aa__=%~dp0


SET TESTING_LIB_APPLICATION_COMMON_PATH=%__aa__CURRENT_SCRIPT_PATH__aa__%
SET TESTING_LIB_APPLICATION_PATH=%TESTING_LIB_APPLICATION_COMMON_PATH%..

SET TESTING_LIB_DOMAIN_PATH=%TESTING_LIB_APPLICATION_PATH%/../TestingLib.Domain
SET TESTING_LIB_DOMAIN_COMMON_PATH=%TESTING_LIB_DOMAIN_PATH%/_Common

CALL "%TESTING_LIB_DOMAIN_COMMON_PATH%/_Pathes.bat"





REM -------------------- Chemins (et scripts) dans TestingLib.Application --------------------------------------

SET TESTING_LIB_APPLICATION_USE_CASES_PATH=%TESTING_LIB_APPLICATION_PATH%/UseCases

SET TESTING_LIB_APPLICATION_COMMON_SERVICES_PATH=%TESTING_LIB_APPLICATION_COMMON_PATH%Services

