@ECHO OFF

SET __ii__CURRENT_SCRIPT_PATH__ii__=%~dp0


SET TESTING_LIB_INFRA_COMMON_PATH=%__ii__CURRENT_SCRIPT_PATH__ii__%
SET TESTING_LIB_INFRA_PATH=%TESTING_LIB_INFRA_COMMON_PATH%..



REM ------ Dépendance vis-à-vis de la couche APPLICATION ----------
SET TESTING_LIB_APPLICATION_PATH=%TESTING_LIB_INFRA_PATH%/../TestingLib.Application
SET TESTING_LIB_APPLICATION_COMMON_PATH=%TESTING_LIB_APPLICATION_PATH%/_Common

CALL "%TESTING_LIB_APPLICATION_COMMON_PATH%/_Pathes.bat"





REM -------------------- Chemins (et scripts) dans TestingLib.Infra --------------------------------------

SET TESTING_LIB_INFRA_REPOSITORIES_PATH=%TESTING_LIB_INFRA_PATH%/Repositories
SET TESTING_LIB_INFRA_REPOSITORIES_MESSAGES_LABEL_REPOSITORY_SCRIPT=%TESTING_LIB_INFRA_REPOSITORIES_PATH%/MessagesLabelRepository.bat

SET TESTING_LIB_INFRA_DATASETS_PATH=%TESTING_LIB_INFRA_PATH%/DataSets
SET TESTING_LIB_INFRA_DATASETS_IN_MEMORY_PATH=%TESTING_LIB_INFRA_DATASETS_PATH%/InMemory

SET TESTING_LIB_INFRA_DI_PATH=%TESTING_LIB_INFRA_PATH%/DI

SET TESTING_LIB_INFRA_SERVICES_PATH=%TESTING_LIB_INFRA_PATH%/Services
SET TESTING_LIB_INFRA_DISK_ELEMENTS_SERVICE_SCRIPT=%TESTING_LIB_INFRA_SERVICES_PATH%/DiskElementsService.bat



REM -------------------------------------------------------------------------------------------------------

SET FLAG_TESTING_LIB_INFRA_COMMON_PATHES_EXECUTED=yes