@ECHO OFF

SET __ii__CURRENT_SCRIPT_PATH__ii__=%~dp0


SET TESTING_LIB_INFRA_COMMON_PATH=%__ii__CURRENT_SCRIPT_PATH__ii__%
SET TESTING_LIB_INFRA_PATH=%TESTING_LIB_INFRA_COMMON_PATH%..

SET TESTING_LIB_APPLICATION_PATH=%TESTING_LIB_INFRA_PATH%/../TestingLib.Application
SET TESTING_LIB_APPLICATION_COMMON_PATH=%TESTING_LIB_APPLICATION_PATH%/_Common

CALL "%TESTING_LIB_APPLICATION_COMMON_PATH%/_Pathes.bat"





REM -------------------- Chemins (et scripts) dans TestingLib.Infra --------------------------------------

SET TESTING_LIB_INFRA_INIT_SCRIPT=%TESTING_LIB_INFRA_PATH%/_Init.bat

SET TESTING_LIB_INFRA_RESPOSITORIES_PATH=%TESTING_LIB_INFRA_PATH%/Repositories

SET TESTING_LIB_INFRA_DATASETS_PATH=%TESTING_LIB_INFRA_PATH%/DataSets
SET TESTING_LIB_INFRA_DATASETS_IN_MEMORY_PATH=%TESTING_LIB_INFRA_DATASETS_PATH%/InMemory

SET TESTING_LIB_INFRA_API_PATH=%TESTING_LIB_INFRA_PATH%/API
SET TESTING_LIB_INFRA_API_FRONT_CONTROLLER_SCRIPT=%TESTING_LIB_INFRA_API_PATH%/_FrontController.bat
SET TESTING_LIB_INFRA_API_ENUMS_PATH=%TESTING_LIB_INFRA_API_PATH%/Enums

SET TESTING_LIB_INFRA_DI_PATH=%TESTING_LIB_INFRA_PATH%/DI



REM -------------------------------------------------------------------------------------------------------

SET FLAG_TESTING_LIB_INFRA_COMMON_PATHES_EXECUTED=yes