@ECHO OFF

IF DEFINED __TESTING_INFRA_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TESTING_INFRA_COMMON_PATHES_EXECUTED__=yes


SET __ii__CURRENT_SCRIPT_PATH__ii__=%~dp0


SET TESTING_INFRA_COMMON_PATH=%__ii__CURRENT_SCRIPT_PATH__ii__%
SET TESTING_INFRA_PATH=%TESTING_INFRA_COMMON_PATH%..


REM PONT VERS Transverse.Infra
CALL "%TESTING_INFRA_COMMON_PATH%_PathesToTransverse.bat"




REM ------ Dépendance vis-à-vis de la couche APPLICATION ----------
SET TESTING_APPLICATION_PATH=%TESTING_INFRA_PATH%/../Application
SET TESTING_APPLICATION_COMMON_PATH=%TESTING_APPLICATION_PATH%/_Common

CALL "%TESTING_APPLICATION_COMMON_PATH%/_Pathes.bat"





REM -------------------- Chemins (et scripts) dans zzzTesting/Infra --------------------------------------

SET TESTING_INFRA_REPOSITORIES_PATH=%TESTING_INFRA_PATH%/Repositories

SET TESTING_INFRA_DATASETS_PATH=%TESTING_INFRA_PATH%/DataSets
SET TESTING_INFRA_DATASETS_IN_MEMORY_PATH=%TESTING_INFRA_DATASETS_PATH%/InMemory

SET TESTING_INFRA_DI_PATH=%TESTING_INFRA_PATH%/DI