@ECHO OFF

IF DEFINED __TESTING_APPLICATION_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TESTING_APPLICATION_COMMON_PATHES_EXECUTED__=yes


SET __aa__CURRENT_SCRIPT_PATH__aa__=%~dp0


SET TESTING_APPLICATION_COMMON_PATH=%__aa__CURRENT_SCRIPT_PATH__aa__%
SET TESTING_APPLICATION_PATH=%TESTING_APPLICATION_COMMON_PATH%..


REM PONT VERS Transverse.Application
CALL "%TESTING_APPLICATION_COMMON_PATH%_PathesToTransverse.bat"




REM ------ Dépendance vis-à-vis de la couche DOMAIN ----------
SET TESTING_DOMAIN_PATH=%TESTING_APPLICATION_PATH%/../Domain
SET TESTING_DOMAIN_COMMON_PATH=%TESTING_DOMAIN_PATH%/_Common

CALL "%TESTING_DOMAIN_COMMON_PATH%/_Pathes.bat"







REM -------------------- Chemins (et scripts) dans zzzTesting/Application --------------------------------------

SET TESTING_APPLICATION_USE_CASES_PATH=%TESTING_APPLICATION_PATH%/UseCases
SET TESTING_APPLICATION_USE_CASES_MAPPERS_PATH=%TESTING_APPLICATION_USE_CASES_PATH%/Mappers

SET TESTING_APPLICATION_USE_CASES_MAPPERS_DOMAIN_TO_NOT_DOMAIN_SCRIPT=%TESTING_APPLICATION_USE_CASES_MAPPERS_PATH%/DomainToNotDomain.bat

SET TESTING_APPLICATION_ENUMS=%TESTING_APPLICATION_PATH%/Enums
SET TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_SCRIPT=%TESTING_APPLICATION_ENUMS%/AssertionResult.bat
