@ECHO OFF

REM =================== LE PONT VERS Transverse.Application ===================

IF DEFINED __TESTING_APPLICATION_COMMON_PATHES_TO_TRANSVERSE_EXECUTED__ GOTO :EOF
SET __TESTING_APPLICATION_COMMON_PATHES_TO_TRANSVERSE_EXECUTED__=yes


SET x_CURRENT_SCRIPT_PATH_xtsttapp=%~dp0


SET TESTING_APPLICATION_COMMON_PATH=%x_CURRENT_SCRIPT_PATH_xtsttapp%
SET TESTING_APPLICATION_PATH=%TESTING_APPLICATION_COMMON_PATH%..

SET TESTING_PATH=%TESTING_APPLICATION_PATH%/..
SET TRANSVERSE_PATH=%TESTING_PATH%/..

SET TRANSVERSE_APPLICATION_PATH=%TRANSVERSE_PATH%/Transverse.Application
SET TRANSVERSE_APPLICATION_COMMON_PATH=%TRANSVERSE_APPLICATION_PATH%/_Common


REM ATTENTION QUAND MÊME, ICI ON NE POINTE QUE SUR du Transverse.Application, pas autre chose !!
CALL "%TRANSVERSE_APPLICATION_COMMON_PATH%/_Pathes.bat"