@ECHO OFF

REM =================== LE PONT VERS Transverse.UI ===================

IF DEFINED __TESTING_UI_COMMON_PATHES_TO_TRANSVERSE_EXECUTED__ GOTO :EOF
SET __TESTING_UI_COMMON_PATHES_TO_TRANSVERSE_EXECUTED__=yes


SET x_CURRENT_SCRIPT_PATH_xtsttui=%~dp0


SET TESTING_UI_COMMON_PATH=%x_CURRENT_SCRIPT_PATH_xtsttui%
SET TESTING_UI_PATH=%TESTING_UI_COMMON_PATH%..

SET TESTING_PATH=%TESTING_UI_PATH%/..
SET TRANSVERSE_PATH=%TESTING_PATH%/..

SET TRANSVERSE_UI_PATH=%TRANSVERSE_PATH%/Transverse.UI
SET TRANSVERSE_UI_COMMON_PATH=%TRANSVERSE_UI_PATH%/_Common


REM ATTENTION QUAND MÊME, ICI ON NE POINTE QUE SUR du Transverse.UI, pas autre chose !!
CALL "%TRANSVERSE_UI_COMMON_PATH%/_Pathes.bat"
SET TESTING_UI_COMMON_ERRORS_HANDLER_SCRIPT=%TRANSVERSE_UI_COMMON_ERRORS_HANDLER_SCRIPT%
SET TESTING_UI_MESSAGES_MESSAGES_DISPLAYER_SCRIPT=%TRANSVERSE_UI_MESSAGES_MESSAGES_DISPLAYER_SCRIPT%