@ECHO OFF

IF DEFINED __TESTING_UI_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TESTING_UI_COMMON_PATHES_EXECUTED__=yes


SET __iui__CURRENT_SCRIPT_PATH__iui__=%~dp0


SET TESTING_UI_COMMON_PATH=%__iui__CURRENT_SCRIPT_PATH__iui__%
SET TESTING_UI_PATH=%TESTING_UI_COMMON_PATH%..






REM PONT VERS Transverse.UI
CALL "%TESTING_UI_COMMON_PATH%_PathesToTransverse.bat"




REM ------ Dépendance vis-à-vis de la couche APPLICATION ----------
SET TESTING_APPLICATION_PATH=%TESTING_UI_PATH%/../Application
SET TESTING_APPLICATION_COMMON_PATH=%TESTING_APPLICATION_PATH%/_Common

CALL "%TESTING_APPLICATION_COMMON_PATH%/_Pathes.bat"








REM -------------------- Chemins (et scripts) dans zzzTesting/UI --------------------------------------

SET TESTING_UI_DI_PATH=%TESTING_UI_PATH%/DI
SET TESTING_UI_CONTROLLERS_PATH=%TESTING_UI_PATH%/Controllers
SET TESTING_UI_VIEWS_PATH=%TESTING_UI_PATH%/Views
SET TESTING_UI_VIEWMODELS_PATH=%TESTING_UI_PATH%/ViewModels
SET TESTING_UI_COMMON_MESSAGES_PATH=%TESTING_UI_COMMON_PATH%Messages

SET TESTING_UI_CONTROLLERS_FRONT_CONTROLLER_SCRIPT=%TESTING_UI_CONTROLLERS_PATH%/_FrontController.bat

SET TESTING_UI_CONTROLLERS_ENUMS_PATH=%TESTING_UI_CONTROLLERS_PATH%/Enums
SET TESTING_UI_CONTROLLERS_ENUMS_LANG_SCRIPT=%TESTING_UI_CONTROLLERS_ENUMS_PATH%/Lang.bat






REM -------------------------------------------------------------------------------------------------------

SET FLAG_TESTING_UI_COMMON_PATHES_EXECUTED=yes