@ECHO OFF

SET _$$__diapi$_CURRENT_SCRIPT_PATH_$di__$$_=%~dp0

SET TESTING_LIB_API_PATH=%_$$__diapi$_CURRENT_SCRIPT_PATH_$di__$$_%..
SET TESTING_LIB_API_COMMON_PATH=%TESTING_LIB_API_PATH%/_Common

REM Recup. de TESTING_LIB_API_DI_PATH
CALL "%TESTING_LIB_API_COMMON_PATH%/_Pathes.bat"


@REM CALL "%TESTING_LIB_API_DI_PATH%/xxxx.bat" %1 %2 %3 %4 %5 %6 %7 %8 %9