@ECHO OFF

SET __iui__CURRENT_SCRIPT_PATH__iui__=%~dp0


SET TESTING_LIB_UI_COMMON_PATH=%__iui__CURRENT_SCRIPT_PATH__iui__%
SET TESTING_LIB_UI_PATH=%TESTING_LIB_UI_COMMON_PATH%..



REM ------ Dépendance vis-à-vis de la couche APPLICATION ----------
SET TESTING_LIB_APPLICATION_PATH=%TESTING_LIB_UI_PATH%/../TestingLib.Application
SET TESTING_LIB_APPLICATION_COMMON_PATH=%TESTING_LIB_APPLICATION_PATH%/_Common

CALL "%TESTING_LIB_APPLICATION_COMMON_PATH%/_Pathes.bat"








REM -------------------- Chemins (et scripts) dans TestingLib.UI --------------------------------------

SET TESTING_LIB_UI_CONTROLLERS_PATH=%TESTING_LIB_UI_PATH%/Controllers
SET TESTING_LIB_UI_VIEWS_PATH=%TESTING_LIB_UI_PATH%/Views
SET TESTING_LIB_UI_VIEWMODELS_PATH=%TESTING_LIB_UI_PATH%/ViewModels
SET TESTING_LIB_UI_DI_PATH=%TESTING_LIB_UI_PATH%/DI
SET TESTING_LIB_UI_COMMON_MESSAGES_PATH=%TESTING_LIB_UI_COMMON_PATH%Messages

SET TESTING_LIB_UI_CONTROLLERS_FRONT_CONTROLLER_SCRIPT=%TESTING_LIB_UI_CONTROLLERS_PATH%/_FrontController.bat

SET TESTING_LIB_UI_CONTROLLERS_ENUMS_PATH=%TESTING_LIB_UI_CONTROLLERS_PATH%/Enums
SET TESTING_LIB_UI_CONTROLLERS_ENUMS_LANG_SCRIPT=%TESTING_LIB_UI_CONTROLLERS_ENUMS_PATH%/Lang.bat






REM -------------------------------------------------------------------------------------------------------

SET FLAG_TESTING_LIB_UI_COMMON_PATHES_EXECUTED=yes