@ECHO OFF

IF DEFINED __TRANSVERSE_API_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TRANSVERSE_API_COMMON_PATHES_EXECUTED__=yes


SET __xxapi__CURRENT_SCRIPT_PATH__xxapi__=%~dp0

SET TRANSVERSE_API_COMMON_PATH=%__xxapi__CURRENT_SCRIPT_PATH__xxapi__%
SET TRANSVERSE_API_PATH=%TRANSVERSE_API_COMMON_PATH%..



REM ----- Dépendance vis-à-vis de la couche APPLICATION -------
SET TRANSVERSE_APPLICATION_PATH=%TRANSVERSE_API_PATH%/../Transverse.Application
SET TRANSVERSE_APPLICATION_COMMON_PATH=%TRANSVERSE_APPLICATION_PATH%/_Common

CALL "%TRANSVERSE_APPLICATION_COMMON_PATH%/_Pathes.bat"







REM -------------------- Chemins (et scripts) dans Transverse.API --------------------------------------

SET TRANSVERSE_API_DI_PATH=%TRANSVERSE_API_PATH%/DI

