@ECHO OFF

REM ----- DOIT être appelé par zzRun_Tests.bat -----

SET $_$CURRENT_SCRIPT_PATH$_$ru=%~dp0

SET TRANSVERSE_TESTS_INFRA_PATH=%$_$CURRENT_SCRIPT_PATH$_$ru%
SET TRANSVERSE_TESTS_INFRA_COMMON_PATH=%TRANSVERSE_TESTS_INFRA_PATH%_Common




REM ------------------------------------------------------------------------------------
REM Recup. de TRANSVERSE_TESTS_UNIT_TESTS_SUBPATH
CALL "%TRANSVERSE_TESTS_INFRA_COMMON_PATH%/_Pathes.bat"



REM ----------------------------- CHEMINS où Tester -------------------------------------
SET TRANSVERSE_TESTS_INFRA_SERVICES_UNIT_TESTS_PATH=%TRANSVERSE_TESTS_INFRA_PATH%/Services/%TRANSVERSE_TESTS_UNIT_TESTS_SUBPATH%
SET TRANSVERSE_TESTS_INFRA_SERVICES_UNIT_TESTS_DISK_ELEMENTS_SERVICE_PATH=%TRANSVERSE_TESTS_INFRA_SERVICES_UNIT_TESTS_PATH%

SET TRANSVERSE_TESTS_INFRA_UNIT_TESTS_PATH=%TRANSVERSE_TESTS_INFRA_PATH%/%TRANSVERSE_TESTS_UNIT_TESTS_SUBPATH%
SET TRANSVERSE_TESTS_INFRA_UNIT_TESTS_7_ZIP_PATH=%TRANSVERSE_TESTS_INFRA_UNIT_TESTS_PATH%
SET TRANSVERSE_TESTS_INFRA_UNIT_TESTS_DATE_TIME_PATH=%TRANSVERSE_TESTS_INFRA_UNIT_TESTS_PATH%



REM ============ RUN TESTS ==========================

CALL "%TRANSVERSE_TESTS_INFRA_SERVICES_UNIT_TESTS_DISK_ELEMENTS_SERVICE_PATH%/DiskElementsServiceTests.bat"
CALL "%TRANSVERSE_TESTS_INFRA_UNIT_TESTS_7_ZIP_PATH%/7ZipTests.bat"
CALL "%TRANSVERSE_TESTS_INFRA_UNIT_TESTS_DATE_TIME_PATH%/DateTimeTests.bat"



REM ==================================================