@ECHO OFF

IF DEFINED __TESTING_DOMAIN_COMMON_ENUMS_ASSERTION_RESULT_EXECUTED__ GOTO :EOF
SET __TESTING_DOMAIN_COMMON_ENUMS_ASSERTION_RESULT_EXECUTED__=yes


REM --- Id des résultats d'assertion ---
SET TESTING_ASSERTION_RESULT_SUCCESS_ID=GOOD_MATCH
SET TESTING_ASSERTION_RESULT_FAILURE_ID=BAD_MATCH