@ECHO OFF

IF DEFINED __TESTING_DOMAIN_COMMON_ENUMS_LANG_EXECUTED__ GOTO :EOF
SET __TESTING_DOMAIN_COMMON_ENUMS_LANG_EXECUTED__=yes


REM --- ID des langues ---
SET TESTING_LANG_US_ID=US
SET TESTING_LANG_FR_ID=FR