@ECHO OFF

SET CURRENT_SCRIPT_PATH=%~dp0
SET TESTS_COMMON_PATH=%CURRENT_SCRIPT_PATH%../../Transverse._Common
SET TESTS_DOMAIN_PATH=%CURRENT_SCRIPT_PATH%../../Transverse.Domain

REM Recup. de SRC_PATH
CALL "%TESTS_COMMON_PATH%/_Pathes.bat"


SET SRC_UI_PATH=%SRC_PATH%/Transverse.UI
SET SRC_UI_MESSAGES_PATH=%SRC_UI_PATH%/Messages

