@ECHO OFF

SET CURRENT_SCRIPT_PATH=%~dp0
@REM SET COMMON_PATHES_PATH=%CURRENT_SCRIPT_PATH%../../Transverse._Common
@REM CALL "%COMMON_PATHES_PATH%/_Pathes.bat"

SET TESTS_DOMAIN_PATH=%CURRENT_SCRIPT_PATH%../../Transverse.Domain