@REM @REM @ECHO OFF

IF NOT DEFINED PACKAGE_TYPE (
  ECHO.
  ECHO LA VAR D'ENVIRONNEMENT  PACKAGE_TYPE  DOIT ETRE DEFINIE !
  ECHO   VALEURS ATTENDUES : PROD ou DEV
  ECHO.
  PAUSE
  GOTO :EOF
)

SET __CURRENT_SCRIPT_PATH_pckg__=%~dp0


SET FOLDER_PATH_TO_PACKAGE=%__CURRENT_SCRIPT_PATH_pckg__%..


REM --------------------------------------
SET LIB_NAME=Transverse
SET FOLDER_NAME_TO_PACKAGE=Src

SET PACKAGES_PATH=%PACKAGES_ROOT_PATH%/____Packages/%LIB_NAME%/zzDOS

SET PACKAGES_ARCHIVES_SUB_PATH=zzzzzzArchives
SET UNZIPPED_SRC_FOLDER_NAME=Scripts




REM --------------------------------------------------------------------
SET SRC_PATH=%__CURRENT_SCRIPT_PATH_pckg__%
SET TRANSVERSE_INFRA_PATH=%SRC_PATH%/Transverse.Infra

SET TRANSVERSE_INFRA_DATE_TIME_SCRIPT=%TRANSVERSE_INFRA_PATH%/DateTime.bat

REM ----------------** Choix du Zipper **-------------------------------
SET TRANSVERSE_INFRA_ZIP_SCRIPT=%TRANSVERSE_INFRA_PATH%/7Zip.bat


REM ----------------- Nommage du Package a produire --------------------
SET CURRENT_DATE=
CALL "%TRANSVERSE_INFRA_DATE_TIME_SCRIPT%" GetDate CURRENT_DATE "."

SET THE_TIME=
CALL "%TRANSVERSE_INFRA_DATE_TIME_SCRIPT%" GetTime THE_TIME "h" "m" "s"

SET CURRENT_DATE_TIME=%CURRENT_DATE%_%THE_TIME%

SET PACKAGE_NAME=%FOLDER_NAME_TO_PACKAGE%_%CURRENT_DATE_TIME%
IF %PACKAGE_TYPE%. EQU DEV. (
  SET PACKAGE_NAME=%PACKAGE_NAME%-beta
)
SET PACKAGE_PATH=%PACKAGES_PATH%/%PACKAGES_ARCHIVES_SUB_PATH%
SET PACKAGE_FILE=%PACKAGE_PATH%/%PACKAGE_NAME%

IF NOT EXIST "%PACKAGE_PATH%" MD "%PACKAGE_PATH%"




REM ---------------------- CREATION DU PACKAGE -------------------------
ECHO. & ECHO.
CALL "%TRANSVERSE_INFRA_ZIP_SCRIPT%" AddToZip "%PACKAGE_FILE%" "%FOLDER_PATH_TO_PACKAGE%/%LIB_NAME%.*" 
CALL "%TRANSVERSE_INFRA_ZIP_SCRIPT%" AddToZip "%PACKAGE_FILE%" "%FOLDER_PATH_TO_PACKAGE%/_Init.bat" 


REM ----------- SUPPRESSION DE CERTAINS FICHIERS DU PACKAGE ------------
ECHO. & ECHO.
SET TO_REMOVE_1=*.lnk
CALL "%TRANSVERSE_INFRA_ZIP_SCRIPT%" RemoveAllOccurencesFromZip "%PACKAGE_FILE%" "%TO_REMOVE_1%"



REM ------------------- DECOMPRESSION DU PACKAGE -----------------------
REM ---------------- ET RENOMMAGE DU DOSSIER OBTENU de -----------------
REM --------- %FOLDER_NAME_TO_PACKAGE% à %UNZIPPED_SRC_FOLDER_NAME% ---------
ECHO. & ECHO.
PUSHD "%__CURRENT_SCRIPT_PATH_pckg__%"
  CD /D "%PACKAGE_PATH%"
  CD ..
  
  REM -DEMANDE SI SUPPR. ou Non, de la forme dezippee de l'ancien package eventuellement deja existante -
  REM  La Supprimera si on repond Oui !
  IF EXIST "%CD%/%UNZIPPED_SRC_FOLDER_NAME%" RD /S "%CD%/%UNZIPPED_SRC_FOLDER_NAME%"

  REM - DEZIPPAGE dans un dossier %FOLDER_NAME_TO_PACKAGE% -
  ECHO. & ECHO.
  CALL "%TRANSVERSE_INFRA_ZIP_SCRIPT%" UnZipIt "%PACKAGE_FILE%" "%CD%/%FOLDER_NAME_TO_PACKAGE%"


  REM SI ON A REFUSE L'ECRASEMENT (car en effet une question a ete posee suite au RD ... ci-dessus )
  REM c-a-d si %CD%/%UNZIPPED_SRC_FOLDER_NAME% existe encore.
  IF EXIST "%CD%/%UNZIPPED_SRC_FOLDER_NAME%" (
    SET UNZIPPED_SRC_FOLDER_NAME=%UNZIPPED_SRC_FOLDER_NAME%_%CURRENT_DATE_TIME%
  )    
  REN "%FOLDER_NAME_TO_PACKAGE%" "%UNZIPPED_SRC_FOLDER_NAME%"

POPD

PAUSE



:DeployLayer
SETLOCAL
  SET __LIB_NAME__=%~1
  SET __LAYER_NAME__=%~2

(ENDLOCAL
)