@ECHO OFF

SET __CURRENT_SCRIPT_PATH_pckgp__=%~dp0


SET PACKAGES_ROOT_PATH=P:\__LIBS
SET PACKAGE_NAME_SUFFIX=


REM LA VAR D'ENV. LIB_NAME  DOIT ETRE DEFINIE EN AMONT !
REM LA VAR D'ENV. FOLDER_TO_PACKAGE_PATH  DOIT ETRE DEFINIE EN AMONT !
REM LES VARS D'ENV. SUBFOLDER_TO_PACKAGE_NAME et SUBFOLDER2_TO_PACKAGE_NAME
REM sont optionnelles.
REM  >>Voir détail explications dans _PACKAGE_TO.bat
CALL "%__CURRENT_SCRIPT_PATH_pckgp__%/zPACKAGE_TO.bat"
