@ECHO OFF

IF DEFINED __TRANSVERSE_TESTS_APPLICATION_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TRANSVERSE_TESTS_APPLICATION_COMMON_PATHES_EXECUTED__=yes


SET _ta_CURRENT_SCRIPT_PATH_ta_=%~dp0

SET TRANSVERSE_TESTS_APPLICATION_COMMON_PATH=%_ta_CURRENT_SCRIPT_PATH_ta_%
SET TRANSVERSE_TESTS_APPLICATION_PATH=%TRANSVERSE_TESTS_APPLICATION_COMMON_PATH%..

SET TRANSVERSE_TESTS_COMMON_PATH=%TRANSVERSE_TESTS_APPLICATION_PATH%/../Transverse._Common

CALL "%TRANSVERSE_TESTS_COMMON_PATH%/_Pathes.bat"





REM ---------------------------------------------------------------------
SET TRANSVERSE_APPLICATION_PATH=%TRANSVERSE_PATH%/Transverse.Application
SET TRANSVERSE_APPLICATION_COMMON_PATH=%TRANSVERSE_APPLICATION_PATH%/_Common

CALL "%TRANSVERSE_APPLICATION_COMMON_PATH%/_Pathes.bat"