@ECHO OFF

IF DEFINED __TRANSVERSE_INFRA_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TRANSVERSE_INFRA_COMMON_PATHES_EXECUTED__=yes


SET __i__CURRENT_SCRIPT_PATH__i__=%~dp0


SET TRANSVERSE_INFRA_COMMON_PATH=%__i__CURRENT_SCRIPT_PATH__i__%
SET TRANSVERSE_INFRA_PATH=%TRANSVERSE_INFRA_COMMON_PATH%..


REM ------------- Dépendance vis-à-vis de la couche APPLICATION --------------------
SET TRANSVERSE_APPLICATION_PATH=%TRANSVERSE_INFRA_PATH%/../Transverse.Application
SET TRANSVERSE_APPLICATION_COMMON_PATH=%TRANSVERSE_APPLICATION_PATH%/_Common

CALL "%TRANSVERSE_APPLICATION_COMMON_PATH%/_Pathes.bat"





REM -------------------- Chemins (et scripts) dans Transverse.Infra --------------------------------------


SET TRANSVERSE_INFRA_DI_PATH=%TRANSVERSE_INFRA_PATH%/DI
SET TRANSVERSE_INFRA_COMMON_CHECK_FATAL_ERRORS_SCRIPT=%TRANSVERSE_INFRA_COMMON_PATH%CheckFatalErrors.bat

SET TRANSVERSE_INFRA_DISK_ELEMENTS_PATH=%TRANSVERSE_INFRA_PATH%/DiskElements




