@ECHO OFF

IF DEFINED __TRANSVERSE_TESTS_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TRANSVERSE_TESTS_COMMON_PATHES_EXECUTED__=yes


SET _tc_CURRENT_SCRIPT_PATH_tc_=%~dp0

SET TRANSVERSE_TESTS_COMMON_PATH=%_tc_CURRENT_SCRIPT_PATH_tc_%

SET TRANSVERSE_PATH=%TRANSVERSE_TESTS_COMMON_PATH%../../Src
SET TRANSVERSE_COMMON_PATH=%TRANSVERSE_PATH%/Transverse._Common

CALL "%TRANSVERSE_COMMON_PATH%/_Pathes.bat"




REM ----------------------------------------------------------------------

SET TRANSVERSE_TESTS_UNIT_TESTS_SUBPATH=UnitTests
