@ECHO OFF

SET _$$__di$_CURRENT_SCRIPT_PATH_$di__$$_=%~dp0

SET TESTING_LIB_UI_PATH=%_$$__di$_CURRENT_SCRIPT_PATH_$di__$$_%..
SET TESTING_LIB_UI_COMMON_PATH=%TESTING_LIB_UI_PATH%/_Common

REM Recup. de TESTING_LIB_UI_DI_PATH
CALL "%TESTING_LIB_UI_COMMON_PATH%/_Pathes.bat"


CALL "%TESTING_LIB_UI_DI_PATH%/UIDependenciesInjection.bat" %1 %2 %3 %4 %5 %6 %7 %8 %9