@ECHO OFF

IF DEFINED __TRANSVERSE_TESTS_DOMAIN_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TRANSVERSE_TESTS_DOMAIN_COMMON_PATHES_EXECUTED__=yes


SET _td_CURRENT_SCRIPT_PATH_td_=%~dp0

SET TRANSVERSE_TESTS_DOMAIN_COMMON_PATH=%_td_CURRENT_SCRIPT_PATH_td_%
SET TRANSVERSE_TESTS_DOMAIN_PATH=%TRANSVERSE_TESTS_DOMAIN_COMMON_PATH%..

SET TRANSVERSE_TESTS_COMMON_PATH=%TRANSVERSE_TESTS_DOMAIN_PATH%/../Transverse._Common

CALL "%TRANSVERSE_TESTS_COMMON_PATH%/_Pathes.bat"




REM ---------------------------------------------------------------------
SET TRANSVERSE_DOMAIN_PATH=%TRANSVERSE_PATH%/Transverse.Domain
SET TRANSVERSE_DOMAIN_COMMON_PATH=%TRANSVERSE_DOMAIN_PATH%/_Common

CALL "%TRANSVERSE_DOMAIN_COMMON_PATH%/_Pathes.bat"