@ECHO OFF

IF DEFINED __TRANSVERSE_APPLICATION_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TRANSVERSE_APPLICATION_COMMON_PATHES_EXECUTED__=yes


SET __a__CURRENT_SCRIPT_PATH__a__=%~dp0


SET TRANSVERSE_APPLICATION_COMMON_PATH=%__a__CURRENT_SCRIPT_PATH__a__%
SET TRANSVERSE_APPLICATION_PATH=%TRANSVERSE_APPLICATION_COMMON_PATH%..


REM ------------- Dépendance vis-à-vis de la couche DOMAIN --------------------
SET TRANSVERSE_DOMAIN_PATH=%TRANSVERSE_APPLICATION_PATH%/../Transverse.Domain
SET TRANSVERSE_DOMAIN_COMMON_PATH=%TRANSVERSE_DOMAIN_PATH%/_Common

CALL "%TRANSVERSE_DOMAIN_COMMON_PATH%/_Pathes.bat"





REM -------------------- Chemins (et scripts) dans Transverse.Application --------------------------------------

@REM SET TRANSVERSE_APPLICATION_..._PATH=%TRANSVERSE_APPLICATION_PATH%/....



