@ECHO OFF

IF DEFINED __TRANSVERSE_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TRANSVERSE_COMMON_PATHES_EXECUTED__=yes


SET __c__CURRENT_SCRIPT_PATH__c__=%~dp0


SET TRANSVERSE_COMMON_PATH=%__c__CURRENT_SCRIPT_PATH__c__%






REM -------------------- Chemins (et scripts) dans Transverse._Common --------------------------------------

SET TRANSVERSE_COMMON_CHECK_FATAL_ERRORS_SCRIPT=%TRANSVERSE_COMMON_PATH%CheckFatalErrors.bat
SET TRANSVERSE_COMMON_CONSTANTS_SCRIPT=%TRANSVERSE_COMMON_PATH%Constants.bat
SET TRANSVERSE_COMMON_VARS_SCRIPT=%TRANSVERSE_COMMON_PATH%Vars.bat
SET TRANSVERSE_COMMON_STRING_SCRIPT=%TRANSVERSE_COMMON_PATH%String.bat