@ECHO OFF


@REM SET _$$$CURRENT_NAMESPACE$$$_=Testing.Application.UseCases
SET _$$$_CURRENT_SCRIPT_PATH_$$$_=%~dp0


SET TESTING_APPLICATION_COMMON_PATH=%_$$$_CURRENT_SCRIPT_PATH_$$$_%../_Common

REM Recup. de
REM TESTING_APPLICATION_USE_CASES_MAPPERS_DOMAIN_TO_NOT_DOMAIN
REM TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_SCRIPT
REM TESTING_DOMAIN_COMMON_ENUMS_PATH
CALL "%TESTING_APPLICATION_COMMON_PATH%/_Pathes.bat"

REM Recup. de
REM TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_SUCCESS_ID et TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_FAILURE_ID
CALL %TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_SCRIPT%

REM Recup. de TESTING_ASSERTION_RESULT_SUCCESS_ID et TESTING_ASSERTION_RESULT_FAILURE_ID
CALL "%TESTING_DOMAIN_COMMON_ENUMS_PATH%/AssertionResult.bat"




REM ===========================================================================	
Rem %1 : retour par référence de __ASSERTION_RESULT_ID__
Rem %2 : DiskElement

Rem Récup. du résultat de l'assertion.
SET __EXISTS__=
CALL "%TESTING_DISK_ELEMENTS_SERVICE_SCRIPT%" Exists %2 __EXISTS__
IF "%__EXISTS__%." EQU "0." (
  SET __ASSERTION_RESULT_ID__=%TESTING_ASSERTION_RESULT_SUCCESS_ID%
) ELSE  (
  SET __ASSERTION_RESULT_ID__=%TESTING_ASSERTION_RESULT_FAILURE_ID%
)
@REM ECHO __ASSERTION_RESULT_ID__='!__ASSERTION_RESULT_ID__!'  for  DiskElement='%2'


CALL :LoadOutputEnumsConversionTable
SET __APPLICATION_ASSERTION_RESULT_ID__=
CALL "%TESTING_COMMON_VARS_SCRIPT%" GetVarValue "ENUM_CONVERSION_" "!__ASSERTION_RESULT_ID__!" __APPLICATION_ASSERTION_RESULT_ID__
CALL "%TESTING_COMMON_CHECK_FATAL_ERRORS_SCRIPT%" CheckVarExists "__APPLICATION_ASSERTION_RESULT_ID__"



SET %1=!__APPLICATION_ASSERTION_RESULT_ID__!

GOTO :EOF



REM ============================================== LOCAL FUNCTIONS ======================================================

:LoadOutputEnumsConversionTable
  SET ENUM_CONVERSION_%TESTING_ASSERTION_RESULT_SUCCESS_ID%=%TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_SUCCESS_ID%
  SET ENUM_CONVERSION_%TESTING_ASSERTION_RESULT_FAILURE_ID%=%TESTING_APPLICATION_ENUMS_ASSERTION_RESULT_FAILURE_ID%
GOTO :EOF
