@ECHO OFF

IF DEFINED __TRANSVERSE_UI_COMMON_PATHES_EXECUTED__ GOTO :EOF
SET __TRANSVERSE_UI_COMMON_PATHES_EXECUTED__=yes


SET __xx__CURRENT_SCRIPT_PATH__xx__=%~dp0

SET TRANSVERSE_UI_COMMON_PATH=%__xx__CURRENT_SCRIPT_PATH__xx__%
SET TRANSVERSE_UI_PATH=%TRANSVERSE_UI_COMMON_PATH%..



REM ----- Dépendance vis-à-vis de la couche APPLICATION -------
SET TRANSVERSE_APPLICATION_PATH=%TRANSVERSE_UI_PATH%/../Transverse.Application
SET TRANSVERSE_APPLICATION_COMMON_PATH=%TRANSVERSE_APPLICATION_PATH%/_Common

CALL "%TRANSVERSE_APPLICATION_COMMON_PATH%/_Pathes.bat"






REM -------------------- Chemins (et scripts) dans Transverse.UI --------------------------------------

SET TRANSVERSE_UI_MESSAGES_PATH=%TRANSVERSE_UI_PATH%/Messages
SET TRANSVERSE_UI_DI_PATH=%TRANSVERSE_UI_PATH%/DI

SET TRANSVERSE_UI_MESSAGES_MESSAGES_DISPLAYER_SCRIPT=%TRANSVERSE_UI_MESSAGES_PATH%/MessagesDisplayer.bat

SET TRANSVERSE_UI_COMMON_ERRORS_HANDLER_SCRIPT=%TRANSVERSE_UI_COMMON_PATH%/ErrorsHandler.bat


