@ECHO OFF


SET __TESTING_PATH__=%~dp0



SET __TESTING_UI_PATH__=%__TESTING_PATH__%UI
SET __TESTING_UI_COMMON_PATH__=%__TESTING_UI_PATH__%/_Common
REM Recup. de TESTING_UI_COMMON_ERRORS_HANDLER_SCRIPT
CALL "%__TESTING_UI_COMMON_PATH__%/_Pathes.bat"
SET __ERRORS_HANDLER__=%TESTING_UI_COMMON_ERRORS_HANDLER_SCRIPT%


CALL "%__TESTING_PATH__%API/_Init.bat" "%__ERRORS_HANDLER__%"
CALL "%__TESTING_PATH__%UI/_Init.bat" "%__ERRORS_HANDLER__%"
CALL "%__TESTING_PATH__%Infra/_Init.bat" "%__ERRORS_HANDLER__%"