@ECHO OFF


SET _$$$CURRENT_NAMESPACE$$$_=TestingLib.Infra.API.Controllers
SET _$$$_CURRENT_SCRIPT_PATH_$$$_=%~dp0

SET TESTING_LIB_INFRA_PATH=%_$$$_CURRENT_SCRIPT_PATH_$$$_%../..
SET TESTING_LIB_INFRA_COMMON_PATH=%TESTING_LIB_INFRA_PATH%/_Common

REM Recup. de TESTING_LIB_APPLICATION_USE_CASES_PATH et TESTING_LIB_INFRA_API_ENUMS_PATH, TESTING_LIB_DOMAIN_COMMON_ENUMS_PATH
CALL "%TESTING_LIB_INFRA_COMMON_PATH%/_Pathes.bat"


Rem Recup. de TESTING_LIB_INFRA_API_ENUMS__ASSERTION_RESULT_SUCCESS_ID, etc...
CALL "%TESTING_LIB_INFRA_API_ENUMS_PATH%/AssertionResult.bat"

Rem Recup. de TESTING_LIB_ASSERTION_RESULT_SUCCESS_ID, etc...
CALL "%TESTING_LIB_DOMAIN_COMMON_ENUMS_PATH%/AssertionResult.bat"





@REM REM ==================== FUNCTION CALL ====================================	
CALL :LoadOutputEnumsConversionTable

IF %1. EQU GetEqualityAssertionResult. (
  Rem --- Appel du UseCase ---
  SET __GET_EQUALITY_ASSERTION_RESULT_USE_CASE_RESPONSE__=
  CALL "%TESTING_LIB_APPLICATION_USE_CASES_PATH%/AssertionResultGetEqualityUseCase.bat" %3 %4 __GET_EQUALITY_ASSERTION_RESULT_USE_CASE_RESPONSE__

  Rem --- Conversion de Enums internes au Domaine vers Enums exposés --- 
  SET __ASSERTION_RESULT__=
  CALL "%TESTING_LIB_COMMON_PATH%/Vars.bat" GetVarValue "ENUM_CONVERSION_" "!__GET_EQUALITY_ASSERTION_RESULT_USE_CASE_RESPONSE__!" __ASSERTION_RESULT__

  Rem Renvoi par référence, du résultat de l'assertion (format Domaine vers format Infra/API)
  SET %2=!__ASSERTION_RESULT__!
)

GOTO :EOF



REM ============================================== LOCAL FUNCTIONS ======================================================

:LoadOutputEnumsConversionTable
  SET "ENUM_CONVERSION_%TESTING_LIB_ASSERTION_RESULT_SUCCESS_ID%=%TESTING_LIB_INFRA_API_ENUMS__ASSERTION_RESULT_SUCCESS_ID%"
  SET "ENUM_CONVERSION_%TESTING_LIB_ASSERTION_RESULT_FAILURE_ID%=%TESTING_LIB_INFRA_API_ENUMS__ASSERTION_RESULT_FAILURE_ID%"
GOTO :EOF